# NumPy Data Types

- strings - "ABCD"
- integer -  1, 0, -1
- float -  1.2, 42.42
- boolean - True or False.
- complex - 1.0 + 2.0j, 1.5 + 2.5j

## NumPy extra data types and refer to data types with one character
- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [3]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


## Creating Arrays With a Defined Data Type

In [4]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [5]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


## Converting Data Type on Existing Arrays

In [7]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [8]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


---

# NumPy Array Copy vs View

The Difference Between Copy and View

- The copy is a new array
- The copy owns the data and any changes made to the copy will not affect original array
- Any changes made to the original array will not affect the copy.


- The view is just a view of the original array.
- The view does not own the data and any changes made to the view will affect the original array
- Any changes made to the original array will affect the view

## COPY

In [11]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()

arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


## VIEW

In [13]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [14]:
# Make Changes in the VIEW
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


## Check if Array Owns it's Data

- Every NumPy array has the attribute base that returns None if the array owns the data.

In [16]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base) # The copy returns None.
print(y.base) # The view returns the original array.

None
[1 2 3 4 5]
