# Random Numbers in NumPy
- Random number does NOT mean a different number every time. 
- Random means something that can not be predicted logically.

## Pseudo Random and True Random

- Computers work on programs, and programs are definitive set of instructions. 
- So it means there must be some algorithm to generate a random number as well.
- If there is a program to generate random number it can be predicted, thus it is not truly random.

**Truly Random Numbers**
- In order to generate a truly random number on our computers we need to get the random data from some outside source. This outside source is generally our keystrokes, mouse movements, data on network etc.
- We do not need truly random numbers, unless its related to security or the basis of application is the randomness

**Pseudo Random Numbers**
- Random numbers generated through a generation algorithm are called pseudo random.

## Generate Random Number

In [43]:
from numpy import random

In [44]:
x = random.randint(1000)

print(x)

901


## Generate Random Float

In [31]:
x = random.rand()

print(x) # float from 0 to 1

0.30090884316654076


## Generate Random Array

### Integers
- The randint() method takes a size parameter where you can specify the shape of an array.

In [34]:
x=random.randint(100, size=(5))

print(x) # 5 random integers from 0 to 100:

[56 87 64 26  0]


In [36]:
# 2-D Array
x = random.randint(100, size=(3, 5)) # 3 rows, each row containing 5 elements

print(x)

[[84 31 14 27 68]
 [32 42 23 90 99]
 [39 25 72  3 87]]


### Floats
- The rand() method also allows you to specify the shape of the array.

In [38]:
x = random.rand(5)

print(x)

[0.54567979 0.30340314 0.52647508 0.5009816  0.13001542]


In [40]:
# 2-D Array
x = random.rand(3, 5) # # 3 rows, each row containing 5 elements

print(x)

[[0.61360565 0.29091476 0.25725793 0.82813693 0.1306133 ]
 [0.68706357 0.79254485 0.99545544 0.89629792 0.43783037]
 [0.59646331 0.96332379 0.235045   0.16811653 0.52298427]]


## Generate Random Number From Array
### choice() 
- Generate a random value based on an array of values.
- Takes an array as a parameter and randomly returns one of the values.

In [41]:
x = random.choice([3, 5, 7, 9])

print(x)

7


In [42]:
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5)) # size parameter to specify the shape of the array.

print(x)

[[5 3 9 7 5]
 [5 3 9 9 5]
 [9 5 7 3 5]]
